import { createGlobalTheme, createThemeContract } from '@vanilla-extract/css'

export const vars = createThemeContract({
  color: {
    brand: null,
    brandHover: null,
    brandMuted: null,
    dark: null,
    white: null,
    nameText: null,
    navbarBg: null,
    semantic: {
      problem: null,
      result: null,
    },
    gray: {
      '50': null,
      '100': null,
      '200': null,
      '300': null,
      '400': null,
      '500': null,
      '700': null,
    },
  },
  font: {
    body: null,
    mono: null,
  },
  fontWeight: {
    normal: null,
    medium: null,
    semibold: null,
    bold: null,
    extrabold: null,
  },
  fontSize: {
    badge: null,
    badgeTitle: null,
    xs: null,
    sm: null,
    base: null,
    lg: null,
    xl: null,
    '2xl': null,
    '3xl': null,
    '4xl': null,
    '5xl': null,
    '6xl': null,
  },
  space: {
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '8': null,
    '12': null,
    '16': null,
    '20': null,
    '24': null,
    '32': null,
  },
  radii: {
    sm: null,
    md: null,
    lg: null,
    xl: null,
    full: null,
  },
  letterSpacing: {
    tighter: null,
    tight: null,
    normal: null,
    wide: null,
    wider: null,
    widest: null,
  },
  lineHeight: {
    none: null,
    tight: null,
    snug: null,
    normal: null,
    relaxed: null,
  },
  transition: {
    fast: null,
    base: null,
    slow: null,
    navbar: null,
  },
  shadow: {
    sm: null,
    card: null,
  },
  zIndex: {
    sticky: null,
    modal: null,
  },
  layout: {
    navbarHeight: null,
  },
})

const staticVars = {
  font: {
    body: "'Inter', sans-serif",
    mono: "'Fira Code', 'Cascadia Code', monospace",
  },
  fontWeight: {
    normal: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extrabold: '800',
  },
  fontSize: {
    badge: '0.5rem',
    badgeTitle: '0.625rem',
    xs: '0.75rem',
    sm: '0.875rem',
    base: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem',
    '5xl': '3rem',
    '6xl': '3.75rem',
  },
  space: {
    '1': '0.25rem',
    '2': '0.5rem',
    '3': '0.75rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '8': '2rem',
    '12': '3rem',
    '16': '4rem',
    '20': '5rem',
    '24': '6rem',
    '32': '8rem',
  },
  radii: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    xl: '16px',
    full: '9999px',
  },
  letterSpacing: {
    tighter: '-0.05em',
    tight: '-0.02em',
    normal: '0',
    wide: '0.05em',
    wider: '0.1em',
    widest: '0.15em',
  },
  lineHeight: {
    none: '1',
    tight: '1.1',
    snug: '1.375',
    normal: '1.5',
    relaxed: '1.625',
  },
  transition: {
    fast: '0.15s ease',
    base: '0.2s ease',
    slow: '0.3s ease',
    navbar: '0.3s ease',
  },
  zIndex: {
    sticky: '50',
    modal: '100',
  },
  layout: {
    navbarHeight: '80px',
  },
}

createGlobalTheme(':root', vars, {
  color: {
    brand: '#5dd98f',
    brandHover: '#4dcc82',
    brandMuted: 'rgba(93, 217, 143, 0.15)',
    dark: '#111111',
    white: '#ffffff',
    nameText: '#e5fff3',
    navbarBg: 'rgba(243, 244, 246, 0.85)',
    semantic: {
      problem: '#e05252',
      result: '#5b8dee',
    },
    gray: {
      '50': '#fafafa',
      '100': '#f3f4f6',
      '200': '#e5e7eb',
      '300': '#d1d5db',
      '400': '#9ca3af',
      '500': '#6b7280',
      '700': '#374151',
    },
  },
  shadow: {
    sm: '0 1px 3px rgba(0,0,0,0.08)',
    card: '0 1px 8px rgba(0,0,0,0.06), 0 0 0 1px rgba(0,0,0,0.04)',
  },
  ...staticVars,
})

createGlobalTheme('[data-theme="dark"]', vars, {
  color: {
    brand: '#1f894e',
    brandHover: '#1a7a45',
    brandMuted: 'rgba(31, 137, 78, 0.15)',
    dark: '#f0f0f0',
    white: '#242424',
    nameText: 'rgba(31, 137, 78, 0.7)',
    navbarBg: 'rgba(28, 28, 28, 0.85)',
    semantic: {
      problem: '#f87171',
      result: '#7fa8f5',
    },
    gray: {
      '50': '#181818',
      '100': '#1c1c1c',
      '200': '#2a2a2a',
      '300': '#3d3d3d',
      '400': '#6b7280',
      '500': '#9ca3af',
      '700': '#d1d5db',
    },
  },
  shadow: {
    sm: '0 1px 3px rgba(0,0,0,0.4)',
    card: '0 1px 8px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.06)',
  },
  ...staticVars,
})
